### ISSUE TITLE
Fvid command not recognized 

### ISSUE THREAD

**Issue by YiffyC** [AlfredoSequeida/fvid#13]
Dear dev,

the fvid command is not recognized after installing via pip3
`command not found: fvid`

Any advice?
Thank you

**Comment by Theelgirl** [comment]
Have you tried putting ``python3 -m`` or ``py -m`` before the rest of the command? Windows requires ``py -m`` before it according to the PyPi page, and ``python3 -m`` might help on linux systems (it helps on my Ubuntu 20.04 VPS sometimes).

Check usage notes at https://pypi.org/project/fvid/

**Comment by AlfredoSequeida** [comment]
@YiffyC I agree with @Theelgirl if you're on a Linux system and that does not work check if you get any errors after installing, maybe you're not installing to PATH.

**Comment by AlfredoSequeida** [comment]
Closed due to not hearing back from OP, if you have any other questions let us know.

**Comment by AlfredoSequeida** [comment]
Closed due to not hearing back from OP, if you have any other questions let us know.

**Comment by YiffyC** [comment]
Dear Alfredo, I did add the folder on the path but still get the same error
