### ISSUE TITLE
Syntax error in line 121 in the fvid.py code

### ISSUE THREAD

**Issue by Halt-Arrtay** [AlfredoSequeida/fvid#31]
In the fvid.py code there is a Syntax Error in line 121,
for filename in sorted(glob.glob(f"{FRAMES_DIR}decoded_frames*.png"), key=os.path.getmtime) :
                                                                                                                  ^
SyntaxError: invalid syntax
 
I don't know how to fix this, can you please advise?

**Comment by Theelgirl** [comment]
Sorry for the late response, can you clone it from the Github and tell me if it works?

**Comment by Theelgirl** [comment]
I assume it's fixed because neither I nor Alfredo seem to be having trouble with it.
