### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by Theelgirl** [AlfredoSequeida/fvid#32]
@AlfredoSequeida There have been a lot of changes since the last release (nearly all within 3 weeks of 0.02), and I was wondering if you could publish a new release to PyPi? It would have to be 1.0.0, as this new release would have passwords, and therefore break backwards compatibility.

**Comment by AlfredoSequeida** [comment]
Definitely, I'll do it by the end of today. Thank you for letting me know.

**Comment by Theelgirl** [comment]
Thanks! It might help to build wheels for Mac/windows/Linux also because of the C extensions.

**Comment by AlfredoSequeida** [comment]
@Theelgirl After testing the latest git version it looks like decode is not outputting a file for me unless I specify the -o option on Linux. Does the same happen for you?

**Comment by Theelgirl** [comment]
It works fine for me on Ubuntu 20.04. Do you have the ffmpeg package installed?

**Comment by Theelgirl** [comment]
Ohhhhh I misread your question, you're using decode. I'll try that now.

**Comment by AlfredoSequeida** [comment]
@Theelgirl What! That's really cool, I'm guessing that is encoded into the file itself. I will definitely have to look into the code to check that out. Thank you for your work on that @dobrosketchkun.

**Comment by AlfredoSequeida** [comment]
@Theelgirl I notice that the latest version is 1.0.1 is that the correct one that you want me to publish to PyPi?

**Comment by Theelgirl** [comment]
@AlfredoSequeida Yes!

**Comment by Theelgirl** [comment]
@AlfredoSequeida Can you actually publish it as 1.0.0? I realized that SemVer doesn't allow for skipping publishing of major versions like 1.0.0, so I changed the changelog to reflect that the most recent version is 1.0.0

**Comment by AlfredoSequeida** [comment]
Got it, I'll get that done by the end of today.

**Comment by Theelgirl** [comment]
Sounds good, thanks!

**Comment by AlfredoSequeida** [comment]
@Theelgirl version 1.0.0 has been published! Thank you for your work you seem to be doing a great job maintaining the repo. If you need me for anything else feel free to ping me.
