### ISSUE TITLE
Switch to H.265 codec

### ISSUE THREAD

**Issue by Theelgirl** [AlfredoSequeida/fvid#39]
https://github.com/AlfredoSequeida/fvid/blob/c20c6877d59da1075de473ab0fc17882132b2786/fvid/fvid.py#L317
So in this line, we tell it to use a H.264 codec, but H.265 is supported by Youtube and basically any other video file sharing/storing service. H.265 allows the resulting file to be much smaller in size, however it won't be able to decode any previously-encoded H.264 files. I propose we either:
- add an -h265 flag allowing users to encode/decode with that
- make the code try h265 first and default back to libx264rbg if that doesn't work
- or, bump fvid to 2.0.0 when/if this is done to signify that h264 encoded videos won't be decodable anymore

Thoughts? I'm learning towards the second option.

**Comment by Theelgirl** [comment]
References:
https://www.videoconverterfactory.com/tips/h265vsh264.html
https://trac.ffmpeg.org/wiki/Encode/H.265
https://support.google.com/youtube/troubleshooter/2888402

**Comment by Theelgirl** [comment]
Update: Just encoded one of my test images, 580KB, with libx265 and the resulting file.mp4 about 31MB, compared to 123MB with libx264rgb.

**Comment by AlfredoSequeida** [comment]
Oh wow, this is cool! I'm not very experienced with video codecs, so I didn't even know there was a better option. I think this is a good idea. What happens if the program was to "try h265 first and default back to libx264rbg"? Does FFmpeg fail and quit by default?

**Comment by Theelgirl** [comment]
So yeah, ffmpeg would fail when it tries to decode a file with the wrong mime type. I'm not totally sure how to catch that fail, but I'm confident it could be done.

**Comment by AlfredoSequeida** [comment]
Yesterday I was working on a project using a program called mediainfo to view file metadata on Linux. Looking up their project, it looks like it also supports mac and windows and we could use it to view video data like a codec and therefore make fvid support virtually any codec by reading that info prior to decoding. I'm willing to bet that ffprobe can do the same thing.

**Comment by Theelgirl** [comment]
@AlfredoSequeida That's a possibility. I think it'd be better to just add an option for a user to be able to specify the codec they want that ffmpeg supports though.

**Comment by Theelgirl** [comment]
Do you mind if I merge zfec error correction and a flag for using H265 into master? (I did the H265 flag yesterday)

**Comment by AlfredoSequeida** [comment]
@Theelgirl I'm definitely ok with the H265 flag and I think that zfec should be good too (good job on that by the way). My only concern about zfec is that with the current zip issue, which I haven't had time to look at, I haven't seen a successful decode form a compressed vid (like from YouTube). So we just have to remember to fix that before pushing out the next version to PyPI.

**Comment by Theelgirl** [comment]
Sounds good.
