### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by ThatIsAPseudo** [AlfredoSequeida/fvid#4]
This project is definitely missing a Readme file to explain people what it does and how cool it is.
Here are some templates :
- https://github.com/dbader/readme-template
- https://github.com/othneildrew/Best-README-Template
- https://github.com/scottydocs/README-template.md

**Comment by YakirOren** [comment]
Hey! I would like to write the readme.

**Comment by AlfredoSequeida** [comment]
@YakirOren Thank you, but it was done this mornig.
