### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by QWERTIOX** [AlfredoSequeida/fvid#40]
Can someone help me with download? Where i need put FFmpeg folder and where i can download libmagic. Where are i need put my file to encode, and where i can find output?

**Comment by AlfredoSequeida** [comment]
FFMPEG can be installed system wide. Just like you would install any other program on your computer. Try to run it without libmagic, I believe that with the most recent update that might no longer be needed. Look at the instructions for encoding / decoding. But the general rule is that if you don't specify an output path, the encoded filed will be in the same directory you ran the program from in a fille called "file.mp4".
