### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by ThatIsAPseudo** [AlfredoSequeida/fvid#5]
There should be a `requirements.txt` file as well as a "Dependendies" section in the Readme (#4) to make usage easier (rather than guessing from the code which packages/libraries to install).

**Comment by dtaivpp** [comment]
Small note on this we will probably need an installation section in the readme. In particular MacOS doesn't come with libmagic and I needed to install it via brew. Not sure if this issue happens on other OS'.

**Comment by AlfredoSequeida** [comment]
Fixed with PyPi implementation.
