### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by KasperSvendsenGit** [AlfredoSequeida/fvid#6]
Hi,
I'm getting a syntax error when trying execute. Doesn't seem to be related to file formats... Can you help.

 python fvid.py -i test.mp4 -e
  File "fvid.py", line 90
    f"{FRAMES_DIR}decoded_frames%03d.png"
                                        ^
SyntaxError: invalid syntax

 python fvid.py -i image.jpeg -e
  File "fvid.py", line 90
    f"{FRAMES_DIR}decoded_frames%03d.png"
                                        ^
SyntaxError: invalid syntax

 python fvid.py -i image2.png -e
  File "fvid.py", line 90
    f"{FRAMES_DIR}decoded_frames%03d.png"
                                        ^
SyntaxError: invalid syntax

 python fvid.py -i test.txt  -e
  File "fvid.py", line 90
    f"{FRAMES_DIR}decoded_frames%03d.png"
                                        ^
SyntaxError: invalid syntax

**Comment by YakirOren** [comment]
check the version of python

**Comment by KasperSvendsenGit** [comment]
> check the version of python

I'm running Python 2.7.18, tried running it with Python3 as well, but get different errors with that.
Thanks!

**Comment by YakirOren** [comment]
im trying to figure out the other errors too :/
 #7

**Comment by dtaivpp** [comment]
Hey all post your other errors here. I got this working on macos python 3. One of the issues I ran into is you need to install libmagic. If you have homebrew you can do `brew install libmagic`

Also @KasperSvendsenGit your issue with python 2 is it doesn't have support for 'f' strings so it will need to be run with Python3

**Comment by AlfredoSequeida** [comment]
@KasperSvendsenGit The first thing that comes to mind is what @dtaivpp said. fstrings were implemented with python 3.6. So if you tried python 3 then I would make sure that you have 3.6 or newer.

**Comment by KasperSvendsenGit** [comment]
> @KasperSvendsenGit The first thing that comes to mind is what @dtaivpp said. fstrings were implemented with python 3.6. So if you tried python 3 then I would make sure that you have 3.6 or newer.

Alright now running on Python 3.8.6, it doesn't strictly error out anymore, though I don't get an output file. @dtaivpp Installing libmagic doesn't seem to have changed anything on linux.

![image](https://user-images.githubusercontent.com/52733424/95357351-0f69b780-08c8-11eb-884c-8cfec082c9a9.png)

**Comment by AlfredoSequeida** [comment]
@KasperSvendsenGit I'm glad you got that working. If you're using the latest version from this repo, the project structure has changed so running it like that won't work without some modifications since the entry point has changed. 

The easy fix would be to install it using pip3

`pip3 install fvid`

then you can just run it like:

`fvid -i [input file] -e `

to encode from any directory in your command line

alternatively, you should also be able to call it using the `__main__.py` file

Let me know how that goes for you.

**Comment by KasperSvendsenGit** [comment]
@AlfredoSequeida  I've resolved the problem by running "sudo pip3 install fvid"

Thanks!
